apiVersion: v1
kind: Service
metadata:
  name: finance-agent-api-service
spec:
  selector:
    app: finance-agent
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
