<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Hermes.Extraction-50a70692-c412-43f5-9951-8bd0d94dec5f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.5" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Hermes.Domain\Hermes.Domain.csproj" />
    <ProjectReference Include="..\..\Core\Hermes.EventBus\Hermes.EventBus.csproj" />
  </ItemGroup>
</Project>
