<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.5" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Hermes.Domain\Hermes.Domain.csproj" />
    <ProjectReference Include="..\..\Core\Hermes.EventBus\Hermes.EventBus.csproj" />
  </ItemGroup>

</Project>
