using System;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;
using Hermes.Domain.Email;
using Hermes.Domain.Financial;
using Hermes.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Hermes.Gateway.Controllers;

/// <summary>
/// Manages the company email inbox configuration used by the Hermes Agent
/// to monitor and extract invoices via IMAP/SMTP.
/// </summary>
[ApiController]
[Route("api/hermes/emails")]
public class EmailController : ControllerBase
{
    private readonly HermesDbContext _db;
    private readonly IConfiguration _config;
    private readonly ILogger<EmailController> _logger;

    public EmailController(HermesDbContext db, IConfiguration config, ILogger<EmailController> logger)
    {
        _db = db;
        _config = config;
        _logger = logger;
    }

    // ─────────────────────────────────────────────────────────────
    // POST /api/hermes/emails/configure
    // Configures the company invoices email inbox for the Hermes Agent.
    // Saves credentials in the DB and updates the agent's environment.
    // ─────────────────────────────────────────────────────────────
    [HttpPost("configure")]
    public async Task<IActionResult> Configure([FromBody] ConfigureEmailRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.EmailAddress))
            return BadRequest(new { detail = "Email address is required." });

        if (string.IsNullOrWhiteSpace(request.AppPassword))
            return BadRequest(new { detail = "App password is required." });

        if (string.IsNullOrWhiteSpace(request.ImapHost) || string.IsNullOrWhiteSpace(request.SmtpHost))
            return BadRequest(new { detail = "IMAP and SMTP hosts are required." });

        // 1. Persist / update the configuration in Postgres
        var existing = await _db.LinkedEmailAccounts
            .FirstOrDefaultAsync(a => a.Provider == request.Provider || a.EmailAddress == request.EmailAddress);

        if (existing != null)
        {
            existing.EmailAddress  = request.EmailAddress;
            existing.Provider      = request.Provider ?? "imap";
            existing.AccessToken   = request.AppPassword;   // repurpose: store app password
            existing.RefreshToken  = $"{request.ImapHost}|{request.ImapPort}|{request.SmtpHost}|{request.SmtpPort}";
            existing.IsActive      = true;
            existing.UpdatedAt     = DateTime.UtcNow;
            await _db.SaveChangesAsync();
        }
        else
        {
            var account = new LinkedEmailAccount
            {
                Provider      = request.Provider ?? "imap",
                EmailAddress  = request.EmailAddress,
                AccessToken   = request.AppPassword,
                RefreshToken  = $"{request.ImapHost}|{request.ImapPort}|{request.SmtpHost}|{request.SmtpPort}",
                IsActive      = true,
                CreatedAt     = DateTime.UtcNow,
            };
            _db.LinkedEmailAccounts.Add(account);
            await _db.SaveChangesAsync();
        }

        // 2. Write the .env file that Hermes Agent reads
        //    The agent config.yaml reads ${FINANCE_EMAIL_ADDRESS} etc. from environment.
        //    We write these to the mounted agent .env file so they persist across restarts.
        try
        {
            var agentEnvPath = _config["HermesAgent__EnvPath"] ?? "/agent-data/.env";
            var envDir = Path.GetDirectoryName(agentEnvPath);
            if (!string.IsNullOrEmpty(envDir) && !Directory.Exists(envDir))
                Directory.CreateDirectory(envDir);

            var envContent = $"""
                # Auto-generated by Hermes.Gateway — {DateTime.UtcNow:u}
                FINANCE_EMAIL_ADDRESS={request.EmailAddress}
                FINANCE_EMAIL_APP_PASSWORD={request.AppPassword}
                FINANCE_IMAP_HOST={request.ImapHost}
                FINANCE_IMAP_PORT={request.ImapPort}
                FINANCE_SMTP_HOST={request.SmtpHost}
                FINANCE_SMTP_PORT={request.SmtpPort}
                """;

            await System.IO.File.WriteAllTextAsync(agentEnvPath, envContent);
            _logger.LogInformation("Hermes Agent .env updated at {Path}", agentEnvPath);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not write Hermes Agent .env file. Agent may need a manual restart.");
        }

        // 3. Notify Hermes Agent API to reload configuration (best effort)
        try
        {
            var agentApiUrl = _config["HermesAgent__BaseUrl"] ?? "http://hermes-agent:8642";
            var agentApiKey = _config["HermesAgent__ApiKey"];

            using var http = new HttpClient();
            http.DefaultRequestHeaders.Add("Authorization", $"Bearer {agentApiKey}");

            // Signal the agent to reload email gateway config
            var reloadResponse = await http.PostAsJsonAsync(
                $"{agentApiUrl}/api/gateway/reload",
                new
                {
                    platform      = "email",
                    email_address = request.EmailAddress,
                    email_password= request.AppPassword,
                    imap_host     = request.ImapHost,
                    imap_port     = request.ImapPort,
                    smtp_host     = request.SmtpHost,
                    smtp_port     = request.SmtpPort,
                });

            _logger.LogInformation("Hermes Agent gateway reload response: {Status}", reloadResponse.StatusCode);
        }
        catch (Exception ex)
        {
            // Non-fatal: the .env file was written; agent will pick it up on next restart
            _logger.LogWarning(ex, "Could not signal Hermes Agent to reload. Configuration saved; restart agent to apply.");
        }

        return Ok(new
        {
            message      = "Email inbox configured successfully. The Hermes Agent will begin monitoring the inbox.",
            emailAddress = request.EmailAddress,
            provider     = request.Provider ?? "imap",
            imapHost     = request.ImapHost,
            smtpHost     = request.SmtpHost,
            pollInterval = 30
        });
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/emails/status
    // Returns the current email inbox configuration status.
    // ─────────────────────────────────────────────────────────────
    [HttpGet("status")]
    public async Task<IActionResult> GetStatus()
    {
        var account = await _db.LinkedEmailAccounts
            .Where(a => a.IsActive)
            .OrderByDescending(a => a.UpdatedAt)
            .Select(a => new
            {
                a.Id,
                a.Provider,
                a.EmailAddress,
                a.IsActive,
                a.LastSyncedAt,
                a.CreatedAt,
                a.UpdatedAt
            })
            .FirstOrDefaultAsync();

        if (account == null)
            return Ok(new { configured = false, message = "No email inbox configured yet." });

        return Ok(new
        {
            configured   = true,
            emailAddress = account.EmailAddress,
            provider     = account.Provider,
            isActive     = account.IsActive,
            lastSyncedAt = account.LastSyncedAt,
            updatedAt    = account.UpdatedAt,
        });
    }

    // ─────────────────────────────────────────────────────────────
    // DELETE /api/hermes/emails/configure
    // Removes the current email configuration.
    // ─────────────────────────────────────────────────────────────
    [HttpDelete("configure")]
    public async Task<IActionResult> RemoveConfiguration()
    {
        var accounts = await _db.LinkedEmailAccounts.ToListAsync();
        if (!accounts.Any()) return NotFound(new { detail = "No email configuration found." });

        _db.LinkedEmailAccounts.RemoveRange(accounts);
        await _db.SaveChangesAsync();
        return Ok(new { message = "Email configuration removed." });
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/emails/inbox
    // Returns a list of processed emails with their classification.
    // Reads from the LinkedEmailAccounts log or proxies from the agent.
    // ─────────────────────────────────────────────────────────────
    [HttpGet("inbox")]
    public async Task<IActionResult> GetInbox([FromQuery] int days = 30)
    {
        // Return invoices classified by email source as "inbox items"
        var since = DateTime.UtcNow.AddDays(-days);
        var invoices = await _db.Invoices
            .Where(i => i.SourceType == "email" && i.CreatedAt >= since)
            .OrderByDescending(i => i.CreatedAt)
            .Take(100)
            .ToListAsync();

        return Ok(invoices.Select(i => new
        {
            id       = i.Id.ToString(),
            subject  = $"Fatura {i.InvoiceNumber} - {i.VendorName}",
            sender   = i.SourceEmail ?? "agente@hermes.local",
            date     = i.CreatedAt.ToString("o"),
            category = MapCategory(i.Status),
            snippet  = $"{i.VendorName} | {i.TotalAmount:C2} | Venc. {i.DueDate?.ToString("dd/MM/yyyy") ?? "N/A"}",
            body     = $"<p><strong>Fornecedor:</strong> {i.VendorName}</p>"
                     + $"<p><strong>Número:</strong> {i.InvoiceNumber}</p>"
                     + $"<p><strong>Total:</strong> {i.TotalAmount:C2} {i.Currency}</p>"
                     + $"<p><strong>Vencimento:</strong> {i.DueDate?.ToString("dd/MM/yyyy") ?? "N/A"}</p>"
                     + $"<p><strong>Status:</strong> {MapCategory(i.Status)}</p>"
        }));
    }

    private static string MapCategory(InvoiceStatus status) => status switch
    {
        InvoiceStatus.Pending        => "accounts_payable",
        InvoiceStatus.Paid           => "paid_bill",
        InvoiceStatus.Overdue        => "accounts_payable",
        InvoiceStatus.Reconciliation => "accounts_payable",
        InvoiceStatus.ReviewRequired => "payment_receipt",
        _                            => "non_financial"
    };

    // ─────────────────────────────────────────────────────────────
    // Legacy: GET /api/hermes/emails/accounts (kept for compatibility)
    // ─────────────────────────────────────────────────────────────
    [HttpGet("accounts")]
    public async Task<IActionResult> GetAccounts()
    {
        return await GetStatus();
    }
}

// ─────────────────────────────────────────────────────────────
// Request DTOs
// ─────────────────────────────────────────────────────────────
public record ConfigureEmailRequest(
    string? Provider,
    string EmailAddress,
    string AppPassword,
    string ImapHost,
    int ImapPort = 993,
    string SmtpHost = "",
    int SmtpPort = 587
);
