using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Hermes.Gateway.Controllers;

/// <summary>
/// Proxies WhatsApp bridge status and QR-code endpoints from the Hermes Agent API
/// to the frontend. The Hermes Agent runs the Baileys bridge internally.
/// </summary>
[ApiController]
[Route("api/hermes/whatsapp")]
public class WhatsAppController : ControllerBase
{
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly IConfiguration _config;
    private readonly ILogger<WhatsAppController> _logger;

    private string AgentBaseUrl => _config["HermesAgent__BaseUrl"] ?? "http://hermes-agent:8642";
    private string AgentApiKey  => _config["HermesAgent__ApiKey"] ?? string.Empty;

    public WhatsAppController(
        IHttpClientFactory httpClientFactory,
        IConfiguration config,
        ILogger<WhatsAppController> logger)
    {
        _httpClientFactory = httpClientFactory;
        _config = config;
        _logger = logger;
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/whatsapp/status
    // Returns WhatsApp bridge connection status from the Hermes Agent.
    // ─────────────────────────────────────────────────────────────
    [HttpGet("status")]
    public async Task<IActionResult> GetStatus()
    {
        try
        {
            var client = CreateAgentClient();
            var response = await client.GetAsync($"http://baileys-bridge:3001/status");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                return Content(content, "application/json");
            }

            // Agent reachable but WhatsApp not yet paired
            return Ok(new { status = "disconnected", paired = false });
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not reach Hermes Agent for WhatsApp status.");
            return Ok(new { status = "disconnected", paired = false, error = "Agent not reachable" });
        }
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/whatsapp/qr
    // Returns the current QR code from the Hermes Agent Baileys bridge.
    // ─────────────────────────────────────────────────────────────
    [HttpGet("qr")]
    public async Task<IActionResult> GetQrCode()
    {
        try
        {
            var client = CreateAgentClient();
            var response = await client.GetAsync($"http://baileys-bridge:3001/qr");

            var content = await response.Content.ReadAsStringAsync();
            if (response.IsSuccessStatusCode || response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                return Content(content, "application/json");
            }

            return Ok(new { status = "disconnected", qr = (string?)null });
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not retrieve WhatsApp QR code from Baileys Bridge.");
            return Ok(new { status = "disconnected", qr = (string?)null });
        }
    }

    // ─────────────────────────────────────────────────────────────
    // POST /api/hermes/whatsapp/disconnect
    // Disconnects the WhatsApp session on the Hermes Agent.
    // ─────────────────────────────────────────────────────────────
    [HttpPost("disconnect")]
    public async Task<IActionResult> Disconnect()
    {
        try
        {
            var client = CreateAgentClient();
            var response = await client.PostAsync($"http://baileys-bridge:3001/disconnect", null);

            return Ok(new { success = response.IsSuccessStatusCode });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error disconnecting WhatsApp from Baileys Bridge.");
            return StatusCode(500, new { error = "Failed to disconnect WhatsApp" });
        }
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/whatsapp/pair-instructions
    // Returns instructions for the admin to pair WhatsApp via terminal.
    // The QR code is generated by running: docker exec -it hermes_agent hermes whatsapp
    // ─────────────────────────────────────────────────────────────
    [HttpGet("pair-instructions")]
    public IActionResult GetPairInstructions()
    {
        return Ok(new
        {
            method  = "terminal",
            command = "docker exec -it hermes_agent hermes whatsapp",
            steps = new[]
            {
                "Abra um terminal e corra: docker exec -it hermes_agent hermes whatsapp",
                "Será apresentado um QR Code no terminal",
                "Abra o WhatsApp no telemóvel → Definições → Dispositivos Associados → Associar Dispositivo",
                "Aponte a câmara para o QR Code no terminal",
                "A sessão fica guardada automaticamente — não precisa de repetir após reiniciar"
            },
            note = "Após o pairing, reinicie o container para activar a bridge: docker compose restart hermes-agent"
        });
    }

    // ─────────────────────────────────────────────────────────────
    // Private helpers
    // ─────────────────────────────────────────────────────────────
    private HttpClient CreateAgentClient()
    {
        var client = _httpClientFactory.CreateClient();
        client.Timeout = TimeSpan.FromSeconds(5);
        if (!string.IsNullOrEmpty(AgentApiKey))
            client.DefaultRequestHeaders.Add("Authorization", $"Bearer {AgentApiKey}");
        return client;
    }
}
