using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Hermes.Gateway.Controllers;

/// <summary>
/// Proxies WhatsApp bridge status and QR-code endpoints from the Hermes Agent API
/// to the frontend. The Hermes Agent runs the Baileys bridge internally.
/// </summary>
[ApiController]
[Route("api/hermes/whatsapp")]
public class WhatsAppController : ControllerBase
{
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly IConfiguration _config;
    private readonly ILogger<WhatsAppController> _logger;

    private string AgentBaseUrl => _config["HermesAgent__BaseUrl"] ?? "http://hermes-agent:8642";
    private string AgentApiKey  => _config["HermesAgent__ApiKey"] ?? string.Empty;

    public WhatsAppController(
        IHttpClientFactory httpClientFactory,
        IConfiguration config,
        ILogger<WhatsAppController> logger)
    {
        _httpClientFactory = httpClientFactory;
        _config = config;
        _logger = logger;
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/whatsapp/status
    // Returns WhatsApp bridge connection status from the Hermes Agent.
    // ─────────────────────────────────────────────────────────────
    [HttpGet("status")]
    public async Task<IActionResult> GetStatus()
    {
        try
        {
            var client = CreateAgentClient();
            var response = await client.GetAsync($"http://baileys-bridge:3001/status");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                return Content(content, "application/json");
            }

            // Agent reachable but WhatsApp not yet paired
            return Ok(new { status = "disconnected", paired = false });
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not reach Hermes Agent for WhatsApp status.");
            return Ok(new { status = "disconnected", paired = false, error = "Agent not reachable" });
        }
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/whatsapp/qr
    // Returns the current QR code from the Hermes Agent Baileys bridge.
    // ─────────────────────────────────────────────────────────────
    [HttpGet("qr")]
    public async Task<IActionResult> GetQrCode()
    {
        try
        {
            var client = CreateAgentClient();
            var response = await client.GetAsync($"http://baileys-bridge:3001/qr");

            var content = await response.Content.ReadAsStringAsync();
            if (response.IsSuccessStatusCode || response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                return Content(content, "application/json");
            }

            return Ok(new { status = "disconnected", qr = (string?)null });
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not retrieve WhatsApp QR code from Baileys Bridge.");
            return Ok(new { status = "disconnected", qr = (string?)null });
        }
    }

    // ─────────────────────────────────────────────────────────────
    // POST /api/hermes/whatsapp/disconnect
    // Disconnects the WhatsApp session on the Hermes Agent.
    // ─────────────────────────────────────────────────────────────
    [HttpPost("disconnect")]
    public async Task<IActionResult> Disconnect()
    {
        try
        {
            var client = CreateAgentClient();
            var response = await client.PostAsync($"http://baileys-bridge:3001/disconnect", null);

            return Ok(new { success = response.IsSuccessStatusCode });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error disconnecting WhatsApp from Baileys Bridge.");
            return StatusCode(500, new { error = "Failed to disconnect WhatsApp" });
        }
    }

    // ─────────────────────────────────────────────────────────────
    // GET /api/hermes/whatsapp/pair-instructions
    // Returns instructions for the admin to pair WhatsApp via terminal.
    // The QR code is generated by running: docker exec -it hermes_agent hermes whatsapp
    // ─────────────────────────────────────────────────────────────
    [HttpGet("pair-instructions")]
    public IActionResult GetPairInstructions()
    {
        return Ok(new
        {
            method  = "terminal",
            command = "docker exec -it hermes_agent hermes whatsapp",
            steps = new[]
            {
                "Abra um terminal e corra: docker exec -it hermes_agent hermes whatsapp",
                "Será apresentado um QR Code no terminal",
                "Abra o WhatsApp no telemóvel → Definições → Dispositivos Associados → Associar Dispositivo",
                "Aponte a câmara para o QR Code no terminal",
                "A sessão fica guardada automaticamente — não precisa de repetir após reiniciar"
            },
            note = "Após o pairing, reinicie o container para activar a bridge: docker compose restart hermes-agent"
        });
    }

    // ─────────────────────────────────────────────────────────────
    // POST /api/hermes/whatsapp/message
    // Receives text messages from the Baileys bridge and routes to Hermes Agent.
    // ─────────────────────────────────────────────────────────────
    public class WhatsAppTextPayload
    {
        public string sender_phone { get; set; } = string.Empty;
        public string text { get; set; } = string.Empty;
    }

    public class TranscriptionResponse
    {
        public string text { get; set; } = string.Empty;
        public string language { get; set; } = string.Empty;
    }

    [HttpPost("message")]
    public async Task<IActionResult> ReceiveMessage(
        [FromBody] WhatsAppTextPayload payload,
        [FromServices] Hermes.Gateway.Services.HermesAgentClient agentClient)
    {
        if (string.IsNullOrWhiteSpace(payload.text)) return BadRequest(new { error = "Empty message" });

        try
        {
            // Inject context about the WhatsApp platform, sender and language requirement
            var messages = new System.Collections.Generic.List<Hermes.Gateway.Services.ChatMessage>
            {
                new("system", $"És o Agente Financeiro Hermes. O utilizador com o número {payload.sender_phone} está a contactar-te pelo WhatsApp. Responde SEMPRE em português europeu (de Portugal), de forma concisa, prestativa e natural. Nunca uses expressões ou vocabulário do português do Brasil."),
                new("user", payload.text)
            };

            var responseText = await agentClient.ChatAsync(messages);

            if (!string.IsNullOrWhiteSpace(responseText))
            {
                // Reply to WhatsApp user via Baileys bridge
                var client = _httpClientFactory.CreateClient();
                var replyBody = new { to = payload.sender_phone, text = responseText };
                await client.PostAsJsonAsync("http://baileys-bridge:3001/send", replyBody);
            }

            return Ok(new { success = true });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to process WhatsApp message from {Sender}", payload.sender_phone);
            return StatusCode(500, new { error = "Internal server error" });
        }
    }

    [HttpPost("audio")]
    public async Task<IActionResult> ReceiveAudio(
        [FromForm] IFormFile file,
        [FromForm] string sender_phone,
        [FromServices] Hermes.Gateway.Services.HermesAgentClient agentClient)
    {
        if (file == null || file.Length == 0) return BadRequest(new { error = "Empty audio file" });
        if (string.IsNullOrWhiteSpace(sender_phone)) return BadRequest(new { error = "Missing sender phone" });

        var client = _httpClientFactory.CreateClient();
        
        try
        {
            // 1. Transcribe the audio via hermes-audio microservice
            using var transcribeContent = new MultipartFormDataContent();
            using var fileStream = file.OpenReadStream();
            using var fileContent = new StreamContent(fileStream);
            transcribeContent.Add(fileContent, "file", file.FileName);
            
            var sttResponse = await client.PostAsync("http://hermes-audio:8000/transcribe", transcribeContent);
            if (!sttResponse.IsSuccessStatusCode)
            {
                _logger.LogError("STT Service failed with status {Status}", sttResponse.StatusCode);
                return StatusCode(500, new { error = "Transcription failed" });
            }
            
            var sttResult = await sttResponse.Content.ReadFromJsonAsync<TranscriptionResponse>();
            if (string.IsNullOrWhiteSpace(sttResult?.text))
            {
                return Ok(new { success = true, note = "Audio transcribed as empty." });
            }
            
            _logger.LogInformation("[WhatsApp Audio] Transcribed: {Text}", sttResult.text);

            // 2. Pass transcribed text to the LLM agent
            var messages = new System.Collections.Generic.List<Hermes.Gateway.Services.ChatMessage>
            {
                new("system", $"És o Agente Financeiro Hermes. O utilizador {sender_phone} enviou uma nota de voz com o seguinte conteúdo transcrito: '{sttResult.text}'. Responde SEMPRE em português europeu (de Portugal), de forma sucinta e natural, adequada para ser lida em voz alta. Nunca uses expressões ou vocabulário do português do Brasil."),
                new("user", sttResult.text)
            };

            var responseText = await agentClient.ChatAsync(messages);

            if (!string.IsNullOrWhiteSpace(responseText))
            {
                // 3. Synthesize the LLM text response to an audio buffer
                using var synthContent = new MultipartFormDataContent();
                synthContent.Add(new StringContent(responseText), "text");
                // XTTS uses 'pt' language, voice identity comes from local reference_speaker.wav
                synthContent.Add(new StringContent("pt"), "voice");
                
                var ttsResponse = await client.PostAsync("http://hermes-audio:8000/synthesize", synthContent);
                if (ttsResponse.IsSuccessStatusCode)
                {
                    var audioBytes = await ttsResponse.Content.ReadAsByteArrayAsync();
                    var audioBase64 = Convert.ToBase64String(audioBytes);
                    
                    // 4. Send the audio file back to WhatsApp
                    var replyBody = new { to = sender_phone, audioBase64 = audioBase64, isPTT = true };
                    await client.PostAsJsonAsync("http://baileys-bridge:3001/send", replyBody);
                }
                else
                {
                    _logger.LogError("TTS Service failed to synthesize voice.");
                    // Fallback to text if TTS fails
                    var replyBody = new { to = sender_phone, text = responseText };
                    await client.PostAsJsonAsync("http://baileys-bridge:3001/send", replyBody);
                }
            }

            return Ok(new { success = true });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to process WhatsApp audio from {Sender}", sender_phone);
            return StatusCode(500, new { error = "Internal server error" });
        }
    }

    // ─────────────────────────────────────────────────────────────
    // Private helpers
    // ─────────────────────────────────────────────────────────────
    private HttpClient CreateAgentClient()
    {
        var client = _httpClientFactory.CreateClient();
        client.Timeout = TimeSpan.FromSeconds(5);
        if (!string.IsNullOrEmpty(AgentApiKey))
            client.DefaultRequestHeaders.Add("Authorization", $"Bearer {AgentApiKey}");
        return client;
    }
}
